### ISSUE TITLE
Support formatting multi-line documentation comments to the line width

### ISSUE THREAD

**Issue by mbravenboer** [RelationalAI-oss/Delve_VSCode#3]
In the Julia mode, I can use alt-q to format multi-line comments to the configured line width. I honestly have no idea based on what VSCode does this, but it doesn't work for Delve for me, as for example in `stdlib` :

```
doc"""
    proper_subset(R, S)
    R ⊂ S

`R` is a proper subset of `S` if `subset(R, S)` and `R` and `S` are not equal, which means
that there has to be at least one fact in `S` that is not in `R`.
"""
```

**Comment by mdashti** [comment]
Are you using a separate plugin? Maybe [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap)?

**Comment by mbravenboer** [comment]
Ah yes, I didn't realize!

![Screenshot from 2021-02-01 09-42-29](https://user-images.githubusercontent.com/3253266/106496526-d3a7be80-6471-11eb-8bd1-17f01469676f.png)

**Comment by mdashti** [comment]
It's a neat extension!

However, it's pretty simplistic and only take two options into consideration: https://github.com/RelationalAI-oss/Delve_VSCode/blob/master/language-configuration.json#L4-L6

We can only only one pair of `blockComment`. For Julia, they are using `["\"\"\"", "\"\"\""]` (and thus it doesn't work for `#= =#` multi-line comment, even for Julia). However, given this constraint with the Rewrap plugin, it makes sense that we also consider `doc""" ... """` as our main multi-line comment facility.

I've already applied this change and release a new version: `1.0.6`

If you think it's not a good idea (as `Alt+Q` won't work for `/* ... */` Delve comments anymore), please let me know.
